### ISSUE TITLE
"Stop" Button Mutes Only, Does Not Stop Video (Android, Chrome Browser)

### ISSUE THREAD

**Issue by whiskyleigh** [pipe/two#1]
Host: Samsung Galaxy Note 9
Android 10 

Guest: Samsung Galaxy S8
Android 9

Browser: Chrome

In Chrome, the “Stop” button kills audio, but not video. Once I hit stop, the Guest User and I were muted, but video continued. Happened on both calls.

**Comment by steely-glint** [comment]
Ugh, yep. 
I've added a simple 'thanks' page that will hang up the call.

Please re-test

**Comment by steely-glint** [comment]
Switched close button to browse away to a 'thanks' page
