### ISSUE TITLE
Various Browser Oddities Noted (Android)

### ISSUE THREAD

**Issue by whiskyleigh** [pipe/two#2]
These maybe just be oddities that will remain unresolved, but as observational notes...

Host: Samsung Galaxy Note 9
Android 10 

Guest: Samsung Galaxy S8
Android 9

Browser:  Various

•	When the Host URL is opened via your FB Messenger DM, via GitHub through the FB browser, “Share in Messenger”, “Copy URL” and “Open in Chrome” are the only available options. A broad “Share” option isn’t there. And if you attempt to open in Chrome from this point, it thinks you are now also a Guest User, and I could effectively have a chat with myself. I think I'll pass. I don’t know how this would behave as the Guest accepting the URL in the FB browser, then attempting to open it in Chrome. I’ll need to test that with a friend as Host and me as Guest.

•	If the Host URL is opened in any other browser besides Chrome (like the aforementioned FB browser) or the native Android browser, the “Allow Audio/Video” prompt does NOT seem to trigger. I’ll run it through a few more times to check this.

**Comment by steely-glint** [comment]
I think this is a quirk of facebook's embedded browser.
I added some code to try to detect the embedded browser and ask the user to switch to the native OS browser (chrome in your case) 

Please re-test.

(Also it is becoming clear to me that the most valuable URL passing mechanism is probably going to be SMS - if both parties have the FB app, they will probably just use that)

**Comment by steely-glint** [comment]
Added code to do popups when an unsuitable browser is used.
